use_frameworks!

target 'YFTestKit_Example' do
  pod 'YFTestKit', :path => '../'

  target 'YFTestKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
